# Generated by Django 5.1.4 on 2026-05-05 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0004_add_codici_gestionali"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Etichetta libera (es: 'Master clienti 2026', 'Scadenze IVA Q1').",
                        max_length=120,
                    ),
                ),
                ("file", models.FileField(upload_to="importazione/%Y/%m/")),
                (
                    "sheet_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome foglio Excel (vuoto = primo foglio).",
                        max_length=120,
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("bozza", "Bozza"),
                            ("mappata", "Colonne mappate"),
                            ("revisionata", "Match revisionato"),
                            ("applicata", "Applicata"),
                            ("annullata", "Annullata"),
                        ],
                        db_index=True,
                        default="bozza",
                        max_length=15,
                    ),
                ),
                (
                    "consente_creazione",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, le righe non matchate creano nuove anagrafiche. Da usare solo per il file master iniziale.",
                    ),
                ),
                (
                    "column_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mapping {nome_colonna_file: campo_target}. campo_target può essere un campo Anagrafica o 'extra:<chiave>' per DatoImportato.",
                    ),
                ),
                (
                    "header_row",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Indice (1-based) della riga di intestazione nel foglio.",
                    ),
                ),
                (
                    "riepilogo",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Statistiche finali (n. create, aggiornate, skip, errori).",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "creato_da",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessione di import",
                "verbose_name_plural": "Sessioni di import",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AnagraficaAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "denominazione_alias",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "fonte",
                    models.CharField(
                        blank=True,
                        help_text="Origine dell'alias: 'manuale', 'import:<id_sessione>', ecc.",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anagrafica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alias",
                        to="anagrafica.anagrafica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alias anagrafica",
                "verbose_name_plural": "Alias anagrafiche",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("anagrafica", "denominazione_alias"),
                        name="uniq_alias_per_anagrafica",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_riga",
                    models.PositiveIntegerField(
                        help_text="Indice (1-based) della riga nel foglio originale."
                    ),
                ),
                (
                    "dati_grezzi",
                    models.JSONField(
                        help_text="Cella per cella: {nome_colonna: valore}."
                    ),
                ),
                (
                    "contesto_sezione",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Contesto dedotto dalla riga-intestazione di sezione (es. tipo_soggetto, regime_contabile, contabilita).",
                    ),
                ),
                (
                    "confidenza",
                    models.FloatField(
                        default=0.0,
                        help_text="0.0-1.0. 1.0 = match esatto su codice univoco.",
                    ),
                ),
                (
                    "metodo_match",
                    models.CharField(
                        blank=True,
                        help_text="Es: 'codice_cli', 'codice_multi', 'codice_fiscale', 'denominazione_esatta', 'fuzzy', 'alias', 'manuale'.",
                        max_length=30,
                    ),
                ),
                (
                    "decisione",
                    models.CharField(
                        choices=[
                            ("auto_match", "Match automatico"),
                            ("confermato", "Match confermato dall'utente"),
                            ("nuova", "Crea nuova anagrafica"),
                            ("skip", "Riga ignorata"),
                            ("errore", "Errore"),
                            ("pending", "Da revisionare"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("messaggio_errore", models.TextField(blank=True)),
                (
                    "anagrafica_match",
                    models.ForeignKey(
                        blank=True,
                        help_text="Anagrafica associata (se match trovato o confermato).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_rows",
                        to="anagrafica.anagrafica",
                    ),
                ),
                (
                    "sessione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="righe",
                        to="importazione.importsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riga import",
                "verbose_name_plural": "Righe import",
                "ordering": ("sessione", "numero_riga"),
                "indexes": [
                    models.Index(
                        fields=["sessione", "decisione"],
                        name="importazion_session_ee5639_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DatoImportato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chiave", models.CharField(db_index=True, max_length=80)),
                ("valore", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anagrafica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dati_importati",
                        to="anagrafica.anagrafica",
                    ),
                ),
                (
                    "fonte_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dati_importati",
                        to="importazione.importsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dato importato",
                "verbose_name_plural": "Dati importati",
                "ordering": ("anagrafica", "chiave"),
                "indexes": [
                    models.Index(
                        fields=["anagrafica", "chiave"],
                        name="importazion_anagraf_30147d_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("anagrafica", "chiave", "fonte_session"),
                        name="uniq_dato_importato_per_fonte",
                    )
                ],
            },
        ),
    ]
