# Generated by Django 5.1.4 on 2026-04-14 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Adempimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("BILANCIO_UE", "Bilancio UE")],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "anno_fiscale",
                    models.IntegerField(
                        db_index=True,
                        help_text="Anno fiscale di riferimento (es. 2025 per il bilancio d'esercizio 2025). Pivot per derivare i referenti del cliente.",
                    ),
                ),
                (
                    "anno_esecuzione",
                    models.IntegerField(
                        db_index=True,
                        help_text="Anno in cui l'adempimento viene eseguito (es. 2026).",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anagrafica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adempimenti",
                        to="anagrafica.anagrafica",
                    ),
                ),
                (
                    "responsabile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Esecutore concreto. Libero, non necessariamente un referente del cliente.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adempimenti_eseguiti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Adempimento",
                "verbose_name_plural": "Adempimenti",
                "ordering": ("-anno_esecuzione", "anagrafica__denominazione"),
            },
        ),
        migrations.CreateModel(
            name="AdempimentoBilancioUE",
            fields=[
                (
                    "adempimento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="bilancio_ue",
                        serialize=False,
                        to="adempimenti.adempimento",
                    ),
                ),
                ("data_chiusura_bilancio", models.DateField(blank=True, null=True)),
                ("data_compilazione", models.DateField(blank=True, null=True)),
                ("data_invio_pratica", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bilancio UE",
                "verbose_name_plural": "Bilanci UE",
            },
        ),
        migrations.AddIndex(
            model_name="adempimento",
            index=models.Index(
                fields=["tipo", "anno_esecuzione"], name="adempimenti_tipo_156804_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adempimento",
            index=models.Index(
                fields=["tipo", "anno_fiscale"], name="adempimenti_tipo_8010d5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="adempimento",
            constraint=models.UniqueConstraint(
                fields=("anagrafica", "tipo", "anno_fiscale"),
                name="uniq_adempimento_cliente_tipo_anno_fiscale",
            ),
        ),
    ]
