# Generated by Django 5.1.4 on 2026-05-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adempimenti", "0006_seed_liquidazione_iva_trimestrale"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adempimento",
            new_name="adempimenti_tipo_id_f82114_idx",
            old_name="adempimenti_tipo_ad_anno_idx",
        ),
        migrations.RenameIndex(
            model_name="adempimento",
            new_name="adempimenti_tipo_id_f99ddc_idx",
            old_name="adempimenti_tipo_ad_stato_idx",
        ),
        migrations.RenameIndex(
            model_name="adempimento",
            new_name="adempimenti_data_sc_103a2f_idx",
            old_name="adempimenti_scadenza_stato_idx",
        ),
        migrations.AlterField(
            model_name="adempimento",
            name="anno_fiscale",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="adempimento",
            name="is_demo",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
