# Generated by Django 5.1.4 on 2026-05-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "adempimenti",
            "0007_rename_adempimenti_tipo_ad_anno_idx_adempimenti_tipo_id_f82114_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VistaAdempimentoColonne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vista",
                    models.CharField(
                        choices=[
                            ("singolo", "Singolo periodo"),
                            ("anno", "Anno aggregato"),
                        ],
                        default="singolo",
                        max_length=10,
                    ),
                ),
                (
                    "colonne_codici",
                    models.JSONField(
                        default=list,
                        help_text="Lista ordinata di codici colonna. Vedi `adempimenti.columns.STANDARD_COLUMNS` per i codici disponibili.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viste_colonne",
                        to="adempimenti.tipoadempimentocatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurazione colonne tabella",
                "verbose_name_plural": "Configurazioni colonne tabelle",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tipo", "vista"), name="uniq_vista_colonne_per_tipo"
                    )
                ],
            },
        ),
    ]
