# Generated by Django 5.1.4 on 2026-05-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "adempimenti",
            "0011_merge_0010_stato_colore_error_0010_tipo_abbreviazione_vista_dedicata",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="statoadempimentotipo",
            name="e_predefinito",
            field=models.BooleanField(
                default=False,
                help_text="Copiato dallo Standard (etichetta informativa). Modificabile ed eliminabile.",
            ),
        ),
    ]
