# Generated by Django 5.1.4 on 2026-04-14 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anagrafica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice_interno", models.CharField(max_length=16, unique=True)),
                (
                    "tipo_soggetto",
                    models.CharField(
                        choices=[
                            ("PF", "Persona fisica"),
                            ("PROFEX", "Professionista"),
                            ("DI", "Ditta individuale"),
                            ("SNC", "SNC"),
                            ("SAS", "SAS"),
                            ("SRL", "SRL"),
                            ("SPA", "SPA"),
                            ("ASS", "Associazione"),
                            ("FALL", "Fallimento"),
                        ],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("denominazione", models.CharField(db_index=True, max_length=255)),
                (
                    "codice_fiscale",
                    models.CharField(blank=True, db_index=True, max_length=16),
                ),
                (
                    "partita_iva",
                    models.CharField(blank=True, db_index=True, max_length=11),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("attivo", "Attivo"),
                            ("sospeso", "Sospeso"),
                            ("cessato", "Cessato"),
                        ],
                        db_index=True,
                        default="attivo",
                        max_length=10,
                    ),
                ),
                ("data_inizio_mandato", models.DateField(blank=True, null=True)),
                ("data_fine_mandato", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("indirizzo_via", models.CharField(blank=True, max_length=200)),
                ("indirizzo_civico", models.CharField(blank=True, max_length=20)),
                ("indirizzo_cap", models.CharField(blank=True, max_length=10)),
                ("indirizzo_comune", models.CharField(blank=True, max_length=100)),
                ("indirizzo_provincia", models.CharField(blank=True, max_length=2)),
                (
                    "indirizzo_nazione",
                    models.CharField(blank=True, default="Italia", max_length=50),
                ),
                (
                    "regime_contabile",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ordinario", "Ordinario"),
                            ("semplificato", "Semplificato"),
                            ("forfettario", "Forfettario"),
                            ("non_applicabile", "Non applicabile"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "periodicita_iva",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mensile", "Mensile"),
                            ("trimestrale", "Trimestrale"),
                            ("non_soggetto", "Non soggetto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cognome", models.CharField(blank=True, max_length=100)),
                ("nome", models.CharField(blank=True, max_length=100)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Anagrafica",
                "verbose_name_plural": "Anagrafiche",
                "ordering": ("denominazione",),
            },
        ),
        migrations.CreateModel(
            name="AnagraficaLegame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_legame",
                    models.CharField(
                        choices=[
                            ("socio", "Socio"),
                            ("amministratore", "Amministratore"),
                            ("legale_rappr", "Legale rappresentante"),
                            ("coniuge", "Coniuge"),
                            ("garante", "Garante"),
                            ("altro", "Altro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anagrafica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legami_da",
                        to="anagrafica.anagrafica",
                    ),
                ),
                (
                    "anagrafica_collegata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legami_a",
                        to="anagrafica.anagrafica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legame anagrafico",
                "verbose_name_plural": "Legami anagrafici",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("anagrafica", "anagrafica_collegata", "tipo_legame"),
                        name="uniq_legame_anagrafico",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("anagrafica", models.F("anagrafica_collegata")),
                            _negated=True,
                        ),
                        name="legame_non_autoriferito",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnagraficaReferenteStudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ruolo",
                    models.CharField(
                        choices=[
                            ("addetto_contabilita", "Addetto contabilità"),
                            ("responsabile_consulenza", "Responsabile consulenza"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "principale",
                    models.BooleanField(
                        default=False,
                        help_text="Quando ci sono più referenti dello stesso ruolo, indica quello principale / capo-pratica.",
                    ),
                ),
                ("data_inizio", models.DateField()),
                (
                    "data_fine",
                    models.DateField(
                        blank=True, help_text="Vuoto = ancora in carica.", null=True
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "anagrafica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referenti_studio",
                        to="anagrafica.anagrafica",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anagrafiche_seguite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referente di studio",
                "verbose_name_plural": "Referenti di studio",
                "ordering": ("-data_inizio",),
                "indexes": [
                    models.Index(
                        fields=["anagrafica", "ruolo", "data_inizio"],
                        name="anagrafica__anagraf_4c274c_idx",
                    ),
                    models.Index(
                        fields=["utente", "ruolo", "data_inizio"],
                        name="anagrafica__utente__af68d5_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("data_fine__isnull", True),
                            ("data_fine__gte", models.F("data_inizio")),
                            _connector="OR",
                        ),
                        name="referente_data_fine_non_prima_di_inizio",
                    )
                ],
            },
        ),
    ]
