# Generated by Django 5.1.4 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0003_profilo_fiscale_progressione"),
    ]

    operations = [
        migrations.AddField(
            model_name="anagrafica",
            name="codice_cli",
            field=models.CharField(
                blank=True,
                help_text="COD CLI ANA — progressivo anagrafica unica gestionale (id_oe002_cliente).",
                max_length=16,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="anagrafica",
            name="codice_multi",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="COD MULTI — progressivo ditta nel gestionale di contabilità.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="anagrafica",
            name="codice_gstudio",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="COD GSTU — progressivo nel gestionale registrazione ore (id_bp004_cliente).",
                max_length=16,
            ),
        ),
    ]
