# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0004_add_codici_gestionali"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anagrafica",
            name="tipo_soggetto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PF", "Persona fisica"),
                    ("PROFEX", "Professionista"),
                    ("DI", "Ditta individuale"),
                    ("SNC", "SNC"),
                    ("SAS", "SAS"),
                    ("SRL", "SRL"),
                    ("SPA", "SPA"),
                    ("ASS", "Associazione"),
                    ("FALL", "Fallimento"),
                ],
                db_index=True,
                max_length=8,
            ),
        ),
    ]
