# Generated by Django 5.1.4 on 2026-05-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0005_categoria_tag"),
        ("anagrafica", "0005_tipo_soggetto_blank"),
    ]

    operations = []
