# Generated by Django 5.1.4 on 2026-05-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0006_merge_0005_categoria_tag_0005_tipo_soggetto_blank"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="progressionecontabilitalog",
            new_name="anagrafica__anagraf_a1b1c6_idx",
            old_name="anagrafica_progr_log_idx",
        ),
    ]
