# Generated by Django 5.1.4 on 2026-05-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0010_textchoicelabel_label_micro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anagrafica",
            name="tipo_soggetto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pf", "Persona fisica"),
                    ("profex", "Professionista"),
                    ("di", "Ditta individuale"),
                    ("snc", "SNC"),
                    ("sas", "SAS"),
                    ("srl", "SRL"),
                    ("spa", "SPA"),
                    ("ass", "Associazione"),
                    ("fall", "Fallimento"),
                ],
                db_index=True,
                max_length=8,
            ),
        ),
    ]
