# Generated by Django 5.1.4 on 2026-05-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0011_alter_anagrafica_tipo_soggetto"),
    ]

    operations = [
        migrations.AddField(
            model_name="textchoicelabel",
            name="attivo",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Se False, il codice non compare nei dropdown e non e' selezionabile per nuove anagrafiche, ma quelle esistenti che lo usano restano valide e mostrano comunque la label.",
            ),
        ),
        migrations.AlterField(
            model_name="anagrafica",
            name="contabilita",
            field=models.CharField(
                blank=True,
                default="esterna",
                help_text="Interna = tenuta dallo studio. Esterna = tenuta dal cliente o da terzi.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="anagrafica",
            name="periodicita_iva",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="anagrafica",
            name="regime_contabile",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="anagrafica",
            name="stato",
            field=models.CharField(
                blank=True, db_index=True, default="attivo", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="anagrafica",
            name="tipo_soggetto",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
