# Generated by Django 5.1.4 on 2026-05-14 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0013_rinomina_ruoli_referente"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anagraficareferentestudio",
            name="nome_grezzo",
            field=models.CharField(
                blank=True,
                help_text="Nome libero da risolvere (popolato dagli import quando il nome dell'addetto non corrisponde a un UtenteStudio).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="anagraficareferentestudio",
            name="utente",
            field=models.ForeignKey(
                blank=True,
                help_text="Vuoto = referente non ancora collegato a un utente del sistema (vedi `nome_grezzo`).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anagrafiche_seguite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="anagraficareferentestudio",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("utente__isnull", False),
                    models.Q(("nome_grezzo", ""), _negated=True),
                    _connector="OR",
                ),
                name="referente_utente_o_nome_grezzo",
            ),
        ),
    ]
